application: pincodemap
version: pincodemap-main
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico|js|css))
  expiration: "1d"

- url: /_.*
  script: main.py
  login: admin

- url: /.*
  script: main.py
